version: '3.6'

services:
  db:
    image: mysql:8.0.33
    container_name: db
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password' # why? read: https://bit.ly/3AC59Ge
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    # always use image with wordpress version specified
    # if upgrading then first upgrade from wordpress updater
    # in dashboard, then use same version here
    image: wordpress:6.2.0-php8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DB_NAME
    volumes:
      - ./volumes/wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:stable
    container_name: webserver
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./volumes/wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./volumes/certbot-etc:/etc/letsencrypt
    networks:
      - app-network
  
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    env_file: .env
    volumes:
      - ./volumes/certbot-etc:/etc/letsencrypt
      - ./volumes/wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL_ID --agree-tos --no-eff-email --staging -d $DOMAIN

volumes:
  dbdata:
  wordpress:
  certbot-etc:

networks:
  app-network:
    driver: bridge