version: '3.6'

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./volumes/dbdata:/var/lib/mysql:rw
  
  redis:
    restart: unless-stopped
    image: 'redis:latest'

  wordpress:
    depends_on:
      - db
      - redis
    # always use image with wordpress version specified
    # if upgrading then first upgrade from wordpress updater
    # in dashboard, then use same version here
    image: wordpress:6.2.0-php8.2-fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_TABLE_PREFIX
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_CACHE', true);
          define('WP_REDIS_SCHEME', 'tcp');
          define('WP_REDIS_HOST', 'redis');
          define('WP_REDIS_PORT', '6379');
    volumes:
      - ./volumes/wordpress:/var/www/html:rw
      - ./conf/php.custom.ini:/usr/local/etc/php/conf.d/php.custom.ini:ro

  webserver:
    depends_on:
      - wordpress
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "${WEBSERVER_PORT_EXPOSED:-80}:80"
    volumes:
      - ./nginx-conf-local:/etc/nginx/conf.d:ro
      - ./volumes/wordpress:/var/www/html:ro
      - ./volumes/certbot-conf:/etc/nginx/ssl:ro
  
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    volumes:
      - ./volumes/wordpress:/var/www/html:rw
      - ./volumes/certbot-conf:/etc/letsencrypt:rw
    command: certonly --webroot --webroot-path=/var/www/html --email $EMAIL_ID --agree-tos --no-eff-email --staging -d $DOMAIN

volumes:
  dbdata:
  wordpress:
  certbot-conf:

networks:
  default:
    driver: bridge